name: flutter_wananzhuo
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #  # toast 自己去实现啊
  #  fluttertoast: ^8.0.7
  # 状态管理
  provider: ^5.0.0
  # 网络
  dio: ^4.0.0
  # 管理dio的cookie
  cookie_jar: ^3.0.1
#  dio_cookie_manager: ^2.0.0

  # Flutter中的webview
  webview_flutter: ^2.0.10
  # 上拉下拉空状态的ListView

  flutter_easyrefresh: ^2.2.1
  # sp
  shared_preferences: ^2.0.6
  #  # 其中包括了SpUtil、ScreenUtil、TimelineUtil
  #  flustars: ^2.0.1
  # android 中运行时权限
  permission_handler: ^8.1.4+2

  # 网络缓存图片
  cached_network_image: ^3.1.0

#  # 轮播图 banner  自己去实现啊
#  flutter_swiper: ^1.1.6

  # 类似于今日头条的屏幕适配方案
  flutter_screenutil: ^5.0.0+2


  # 华丽简单的日志打印
  flutter_easylogger: ^2.1.1

  cupertino_icons: ^1.0.2

 # 文件目录
  path_provider: ^2.0.2

  flutter_svg: ^0.22.0

  flutter_spinkit: ^5.0.0

  flutter_cache_manager: ^3.1.2



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/
